services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A backend.analyzer worker -l info
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app

  celery_beat:
    build: .
    command: celery -A backend.analyzer beat -l info
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - GHIDRA_INSTALL_DIR=/opt/ghidra_11.3.2_PUBLIC
      - PYTHONPATH=/app

  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery_worker
    environment:
      - PYTHONPATH=/app
